In [ ]:
! pip install transformers datasets --quiet
from datasets import load_dataset
from transformers import pipeline
from huggingface_hub import notebook_login
notebook_login()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 521.2/521.2 kB 4.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 10.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 12.2 MB/s eta 0:00:00


In [ ]:
from datasets import load_dataset
stsb_multi_mt_train = load_dataset("stsb_multi_mt", name="en", split="train")
stsb_multi_mt_dev = load_dataset("stsb_multi_mt", name="en", split="dev")
stsb_multi_mt_test = load_dataset("stsb_multi_mt", name="en", split="test")

Generating train split:   0%|          | 0/5749 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1379 [00:00<?, ? examples/s]

Generating dev split:   0%|          | 0/1500 [00:00<?, ? examples/s]

In [ ]:
print(stsb_multi_mt_test[1]['sentence1'])
print(stsb_multi_mt_test[1]['sentence2'])
print(stsb_multi_mt_test[1]['similarity_score'])

A group of men play soccer on the beach.
A group of boys are playing soccer on the beach.
3.5999999046325684


# Model1

In [ ]:
from transformers import    DistilBertForSequenceClassification,   DistilBertTokenizer
import torch


model =  DistilBertForSequenceClassification.from_pretrained('vicl/distilbert-base-uncased-finetuned-stsb',num_labels=1)
tokenizer = DistilBertTokenizer.from_pretrained('vicl/distilbert-base-uncased-finetuned-stsb')



DistilBert_predictions=[]
DistilBert_similarity_score=[]
for i in range(100):
  input= tokenizer(stsb_multi_mt_test[i]['sentence1'], stsb_multi_mt_test[i]['sentence2'], padding=True,return_tensors="pt" )
  output = model(**input)
  DistilBert_predictions.append(round(output.logits[0].item(),2))
  DistilBert_similarity_score.append(round(stsb_multi_mt_test[i]['similarity_score'],2))


config.json:   0%|          | 0.00/676 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

In [ ]:
E1=torch.tensor(DistilBert_predictions)

In [ ]:
print(E1)

tensor([3.0800, 3.9800, 4.5100, 4.6000, 2.1400, 1.7600, 4.0700, 2.0600, 2.3900,
        1.8800, 1.8800, 4.7600, 0.8400, 4.3600, 1.9000, 2.3100, 4.6500, 3.0800,
        2.4200, 0.7800, 1.6800, 0.6300, 4.6300, 4.5800, 1.1300, 3.2700, 0.6900,
        4.5300, 0.7800, 3.1300, 2.7900, 4.1900, 0.7400, 4.0800, 3.4300, 0.3100,
        0.7000, 2.1300, 4.4300, 0.6400, 3.6100, 3.2300, 3.2700, 0.4400, 1.7600,
        0.7300, 0.3700, 0.7500, 3.8600, 2.6500, 0.7700, 1.6500, 0.6000, 0.6600,
        1.9100, 0.1300, 3.7400, 1.1800, 3.8700, 1.4600, 4.7300, 0.1200, 4.0900,
        1.0400, 3.5900, 0.6100, 0.2600, 3.5300, 0.1200, 3.9900, 3.1400, 3.5000,
        0.1200, 3.9300, 3.7200, 0.1300, 0.3900, 0.0300, 3.0000, 4.6500, 0.1700,
        0.8400, 2.7200, 1.9700, 0.4000, 3.6000, 3.1500, 4.6000, 2.8400, 1.3400,
        1.9700, 2.7600, 0.4700, 3.7800, 0.9400, 3.8800, 4.0500, 4.0100, 3.0200,
        2.8200])


In [ ]:
DistilBert_similarity_score

In [ ]:
import torch.nn as nn
loss = nn.MSELoss(reduction='mean')
MSE = loss(torch.tensor(E1), torch.tensor(DistilBert_similarity_score))
print(MSE)

tensor(0.4351)


<ipython-input-11-780b5a02b065>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  MSE = loss(torch.tensor(E1), torch.tensor(DistilBert_similarity_score))


# Model2

In [ ]:
from transformers import    BertForSequenceClassification,   BertTokenizer
import torch


model =  BertForSequenceClassification.from_pretrained('yoshitomo-matsubara/bert-base-uncased-stsb',num_labels=1)
tokenizer = BertTokenizer.from_pretrained('yoshitomo-matsubara/bert-base-uncased-stsb')


Bert_predictions=[]
Bert_similarity_score=[]
for i in range(100):
  input= tokenizer(stsb_multi_mt_test[i]['sentence1'], stsb_multi_mt_test[i]['sentence2'], padding=True,return_tensors="pt" )
  output = model(**input)
  Bert_predictions.append(round(output.logits[0].item(),2))
  Bert_similarity_score.append(round(stsb_multi_mt_test[i]['similarity_score'],2))


config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/303 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
E2=torch.tensor(Bert_predictions)

In [ ]:
print(E2)

tensor([3.2900, 3.9400, 4.3900, 4.3200, 1.9700, 2.3600, 3.3400, 2.0000, 2.7500,
        1.4200, 1.4200, 4.6400, 0.8500, 4.1500, 2.3800, 1.8000, 4.2300, 2.9600,
        2.3900, 0.5000, 2.0200, 0.8000, 4.8200, 3.6900, 1.3300, 3.6900, 0.9900,
        3.1700, 0.5800, 3.2500, 2.4000, 4.3000, 1.3300, 3.8300, 2.7900, 0.3600,
        0.6100, 2.1600, 4.3200, 0.8700, 3.6100, 3.4900, 3.1800, 0.6100, 1.7500,
        0.5900, 0.3000, 0.7000, 4.1400, 2.4300, 0.8600, 1.5500, 0.4200, 0.6500,
        1.5500, 0.2600, 4.2400, 1.0800, 3.5800, 1.6800, 4.3700, 0.2200, 3.6700,
        2.0300, 3.7900, 0.7300, 0.2200, 3.5600, 0.0900, 3.6700, 2.9200, 4.2200,
        0.1900, 3.7400, 3.9000, 0.1900, 0.0400, 0.0200, 3.2400, 4.4300, 0.4200,
        0.8500, 2.7400, 2.0300, 0.6800, 2.8200, 3.6500, 4.2400, 3.2600, 1.5100,
        0.7200, 3.3100, 0.4600, 4.1500, 2.5400, 4.2800, 3.3800, 4.4300, 2.9300,
        3.7300])


In [ ]:
import torch.nn as nn
loss = nn.MSELoss(reduction='mean')
MSE = loss(torch.tensor(E2), torch.tensor(Bert_similarity_score))
print(MSE)

tensor(0.3890)


<ipython-input-23-1039a2d44253>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  MSE = loss(torch.tensor(E2), torch.tensor(Bert_similarity_score))


#Model3

In [ ]:
from transformers import    ElectraForSequenceClassification,   ElectraTokenizer
import torch


model =  ElectraForSequenceClassification.from_pretrained('howey/electra-base-stsb',num_labels=1)
tokenizer = ElectraTokenizer.from_pretrained('howey/electra-base-stsb')


Electra_predictions=[]
Electra_similarity_score=[]
for i in range(100):
  input= tokenizer(stsb_multi_mt_test[i]['sentence1'], stsb_multi_mt_test[i]['sentence2'], padding=True,return_tensors="pt" )
  output = model(**input)
  Electra_predictions.append(round(output.logits[0].item(),2))
  Electra_similarity_score.append(round(stsb_multi_mt_test[i]['similarity_score'],2))


config.json:   0%|          | 0.00/840 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
E3=torch.tensor(Electra_predictions)

In [ ]:
print(E3)

tensor([ 2.6300,  3.7800,  5.0500,  5.1300,  1.8700,  1.8700,  3.5300,  1.7500,
         2.6700,  1.7100,  1.7100,  5.2100,  0.5600,  5.0700,  1.7400,  1.7800,
         4.1100,  3.3000,  2.9800,  1.1300,  1.8700,  0.4900,  5.1300,  4.9300,
         1.3900,  3.6100,  0.8600,  2.3100,  0.7300,  2.9700,  3.2100,  4.9400,
         0.7600,  4.7300,  3.6700,  0.4200,  0.4300,  2.7800,  4.8800,  0.7400,
         4.3400,  3.4300,  3.1900,  0.8200,  2.0800,  0.1800,  0.3000,  1.0800,
         4.8000,  2.2600,  1.0200,  1.4300,  0.2600,  0.6300,  1.5700,  0.2000,
         3.5400,  1.3700,  4.5600,  1.1100,  5.2100, -0.0300,  3.9100,  1.2700,
         3.6300,  0.2500,  0.6000,  3.9000,  0.1900,  4.7100,  2.8200,  4.6600,
        -0.0400,  3.9700,  4.1300,  0.3100,  0.2800, -0.0600,  3.1300,  4.5200,
         0.3700,  0.6700,  3.0200,  1.0200,  0.6000,  2.0200,  3.4700,  4.8300,
         3.8200,  1.1900,  1.9400,  3.5600,  0.8500,  4.1600,  2.8700,  4.8500,
         4.4400,  4.2700,  2.5400,  3.44

In [ ]:
import torch.nn as nn
loss = nn.MSELoss(reduction='mean')
MSE = loss(torch.tensor(E3), torch.tensor(Electra_similarity_score))
print(MSE)

tensor(0.3392)


<ipython-input-29-4ee167839564>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  MSE = loss(torch.tensor(E3), torch.tensor(Electra_similarity_score))


#Ensemble

In [ ]:
Et=(E3+E2+E1)/3

In [ ]:
import torch.nn as nn
loss = nn.MSELoss(reduction='mean')
MSE = loss(torch.tensor(Et), torch.tensor(Electra_similarity_score))
print(MSE)

tensor(0.3104)


<ipython-input-31-48d6773a4203>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  MSE = loss(torch.tensor(Et), torch.tensor(Electra_similarity_score))
